name = "BetaReader"
uuid = "e5583720-4bc8-44d1-bd9a-9734450b0166"
authors = ["Eumaeus <cwblackwell@gmail.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
PolytonicGreek = "72b824a7-2b4a-40fa-944c-ac4f345dc63a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"

[compat]
julia = "1"
DocStringExtensions =  "0.8"
Documenter = "0.27"
PolytonicGreek = "0.16"
TestSetExtensions = "2.0"